# Example configuration for RGB2Point training and inference

# Dataset settings
dataset:
  root: ./data
  categories: ["plantonly", "plantonly2", "plant3"]

# Model hyperparameters
# model:
#   num_views: 1
#   point_cloud_size: 2048
#   num_heads: 4
#   dim_feedforward: 2048

model:
  num_views: 1
  point_cloud_size: 2048
  num_heads: 16
  dim_feedforward: 8192
  train_vit: false

# Training options
training:
  batch_size: 4
  num_epochs: 20000
  learning_rate: 5e-4
  scheduler:
    factor: 0.7
    patience: 5
    min_lr: 1e-5
    threshold: 0.01

# Finetuning
finetune:
  ckpt: ckpt/pc1024_three.pth

# Inference
inference:
  model_path: ckpt/20250706_155728/model_epoch9830_score0.0107.pth
  image_path: ./data/ShapeNetRendering/plantonly2/エンレイ4/rendering/エンレイ4_2.JPG
  save_path: result/pi_2_2_0710.ply
