services:
  app:
    build: .
    volumes:
      - ./data:/app/data
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    tty: true
    command: bash
